#!/bin/sh
#
# AUTHOR: Iñigo Marin
#
# DATE: Sat Agosto 21 2021
#
# DESC: Elvi to search Crates.io
# elvis: crates  -- Search Crates  (crates.io)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Crates (crates.io) for cares
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://crates.io"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://crates.io/search?q=${escaped_args}"
fi
