#!/bin/sh
#
# AUTHOR: Iñigo Marin
#
# DATE: Sat Jun 13 2021
#
# DESC: Elvi to search Elitetorrent
# elvis: elitetorrent  -- Search Elitetorrent (elitetorrent.in)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Elitetorrent (elitetorrent.in) for videos
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://elitetorrent.in"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://elitetorrent.in?s=${escaped_args}"
fi
