#!/bin/sh
#
# AUTHOR: Iñigo Marin
#
# DATE: Sat Jun 13 2021
#
# DESC: Elvi to search Sensacine
# elvis: Yadixv  -- Search Yadixv (www.yadivx.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Yadixv (www.yadivx.com) for torrent
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.yadixv.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.yadixv.com/index.php?story=${escaped_args}&do=search&subaction=search"

fi
